import type { Technology } from '../types/wizard.types'
export const TECHNOLOGIES: Technology[] = [
  { id: 'nodejs', label: 'Node.js', icon: 'nodejs', color: 'hsl(142 71% 45%)', colorClass: 'text-emerald-400', bgClass: 'bg-emerald-400/10', borderClass: 'border-emerald-400/30', description: 'JavaScript runtime', versions: [ { label: '22-alpine', value: '22-alpine', recommended: true }, { label: '21-alpine', value: '21-alpine' }, { label: '20-alpine', value: '20-alpine' }, { label: '18-alpine', value: '18-alpine' }, { label: '16-alpine', value: '16-alpine' } ], defaultCommand: 'npm start', defaultPort: 3000 },
  { id: 'python', label: 'Python', icon: 'python', color: 'hsl(207 90% 54%)', colorClass: 'text-blue-400', bgClass: 'bg-blue-400/10', borderClass: 'border-blue-400/30', description: 'General purpose', versions: [ { label: '3.12-slim', value: '3.12-slim', recommended: true }, { label: '3.11-slim', value: '3.11-slim' }, { label: '3.10-slim', value: '3.10-slim' }, { label: '3.9-slim', value: '3.9-slim' }, { label: '3.8-slim', value: '3.8-slim' } ], defaultCommand: 'python app.py', defaultPort: 8000 },
  { id: 'php', label: 'PHP', icon: 'php', color: 'hsl(262 83% 65%)', colorClass: 'text-violet-400', bgClass: 'bg-violet-400/10', borderClass: 'border-violet-400/30', description: 'Web server scripting', versions: [ { label: '8.3-apache', value: '8.3-apache', recommended: true }, { label: '8.2-apache', value: '8.2-apache' }, { label: '8.1-apache', value: '8.1-apache' }, { label: '8.0-apache', value: '8.0-apache' }, { label: '7.4-apache', value: '7.4-apache' } ], defaultCommand: 'apache2-foreground', defaultPort: 80 },
  { id: 'java', label: 'Java', icon: 'java', color: 'hsl(25 95% 53%)', colorClass: 'text-orange-400', bgClass: 'bg-orange-400/10', borderClass: 'border-orange-400/30', description: 'OpenJDK enterprise', versions: [ { label: '21-jdk-slim', value: '21-jdk-slim', recommended: true }, { label: '22-jdk-slim', value: '22-jdk-slim' }, { label: '17-jdk-slim', value: '17-jdk-slim' }, { label: '11-jre-slim', value: '11-jre-slim' }, { label: '8-jdk-alpine', value: '8-jdk-alpine' } ], defaultCommand: 'java -jar app.jar', defaultPort: 8080 },
  { id: 'go', label: 'Go', icon: 'go', color: 'hsl(185 85% 47%)', colorClass: 'text-cyan-400', bgClass: 'bg-cyan-400/10', borderClass: 'border-cyan-400/30', description: 'Fast compiled language', versions: [ { label: '1.23-alpine', value: '1.23-alpine', recommended: true }, { label: '1.22-alpine', value: '1.22-alpine' }, { label: '1.21-alpine', value: '1.21-alpine' }, { label: '1.20-alpine', value: '1.20-alpine' }, { label: '1.19-alpine', value: '1.19-alpine' } ], defaultCommand: './app', defaultPort: 8080 },
]
export const DOCKER_BASE_IMAGES: Record<string, string> = { nodejs: 'node', python: 'python', php: 'php', java: 'openjdk', go: 'golang' }
